wavvapp/sac-frontend

components/cards/Status.tsx, components/ui/Badge.tsx, components/ui/Button.tsx, screens/EditSignal/index.tsx, types/index.ts
=> Fix : status button design

components/cards/UserStatus.tsx
=> feat: update user status component

components/Share.tsx, screens/Home/index.tsx, utils/share.ts
=> Feat: Home badge, setting and share button

components/lists/Friends.tsx, components/lists/Signaling.tsx
=> fix: change signaling list title size

components/cards/UserStatus.tsx
=> refactor: update the text when the signal is off

components/Activity.tsx, screens/EditActivity/index.tsx
=> refactor: fix the editable text font weight

hooks/useSignal.ts, screens/CustomSplashScreen/index.tsx, screens/Home/index.tsx, service/index.ts
=> feat: update signal from the backend

components/ui/Input.tsx, components/vectors/CheckIcon.tsx, screens/EditActivity/index.tsx
=> Feat:add done btn to the edit activity form

components/ui/Button.tsx, screens/EditSignal/index.tsx
=> refactor: add loader state while saving activity status

hooks/useFriends.ts, navigation/index.tsx, types/index.ts
=> fix: remove showing that user has no friends when they do

App.tsx, screens/Authentication/SignUp/CreateCredentials.tsx, screens/Home/index.tsx
=> Feat: add safeAreaView

components/SignalingUser.tsx, components/lists/Signaling.tsx, hooks/useFriends.ts, theme.ts
=> refactor: make offline friends to cover the whole height of the screen

components/lists/Friends.tsx, contexts/StatusContext.tsx, hooks/useFriends.ts, hooks/useSignal.ts, screens/Home/index.tsx, service/index.ts, types/index.ts
=> fix: show signal friends also on the status card

screens/EditSignal/index.tsx
=> fix: go back to home screen when crossmark is checked

components/cards/UserStatus.tsx, screens/EditSignal/index.tsx
=> fix: open the edit screen when the button is clicked instantly

screens/Search/index.tsx
=> refactor: adding spinning icon while adding friends

components/Friend.tsx, components/ui/CheckBox.tsx
=> fix: signal friends when click on the plus icon

contexts/AuthContext.tsx, navigation/index.tsx, screens/Authentication/SignUp/CreateCredentials.tsx, screens/Home/index.tsx, utils/share.ts
=> Fix: only create new user account when username is provided

app.json
=> fix: change the app name to Wavv

contexts/AuthContext.tsx, navigation/index.tsx
=> refactor: properly await loading state

contexts/AuthContext.tsx, navigation/index.tsx, screens/Authentication/SignUp/CreateCredentials.tsx, screens/Authentication/index.tsx
=> fix: log in for new user inconsistency

components/cards/Status.tsx, screens/Search/index.tsx
=> refactor: fix time slot and loading state issues

components/Activity.tsx, components/cards/Status.tsx, components/cards/UserStatus.tsx, components/lists/Friends.tsx, contexts/StatusContext.tsx, screens/EditActivity/index.tsx, screens/EditSignal/index.tsx
=> fix: edit status save inconsistency

screens/Home/index.tsx
=> feat: set zero as default fallback value for points

components/Share.tsx, screens/Home/index.tsx, utils/share.ts
=> fix: pass the username to the sharecard onpress

screens/EditActivity/index.tsx
=> refactor: change edit activity confirmation btn

components/Activity.tsx, components/cards/UserAvailability.tsx, utils/index.ts
=> Feat:  Capitalize first letter on user's activity

components/cards/UserStatus.tsx
=> Fix : Remove unnecessary space on names with first names only in userStatus card

components/AlertDialog.tsx, screens/Home/index.tsx, theme.ts
=> create an offline-popup when there is no internet connection

queries/friends.ts, screens/Search/index.tsx
This PR aims to address the concerns raised by the comment left on the previous PR. https://github.com/wavvapp/sac-frontend/pull/245#discussion_r1904282353
=> hot-fix: update optimistically users correctly when creating friendships

components/AlertDialog.tsx, components/lists/Signaling.tsx, contexts/AuthContext.tsx, hooks/useOfflineHandler.ts, navigation/index.tsx, package-lock.json, package.json, screens/EditSignal/index.tsx, screens/Home/index.tsx, screens/Search/index.tsx, service/index.ts, types/index.ts
=> feat: check the network connectivity

components/lists/Friends.tsx, contexts/AuthContext.tsx, contexts/StatusContext.tsx, queries/signal.ts
=> Fix: the switch button to be stuck in the middle.

service/index.ts
=> send user's current timezone in headers to the backend

components/Activity.tsx, components/ui/Input.tsx, screens/EditActivity/index.tsx
=> Fix: Show the keyboard by default when user is editing the status

components/PerlinNoise/index.tsx, components/lists/Signaling.tsx, screens/Authentication/index.tsx, screens/Home/index.tsx, utils/dimensions.ts
=> Feat: Create dimensions file 

components/UserInfo.tsx, components/cards/UserProfile.tsx, components/ui/UserAvatar.tsx, screens/Settings/index.tsx
=> feat: create user profile component

screens/Settings/index.tsx
=> refactor: update logout button text

components/AlertDialog.tsx
=> Fix: add max-width for the dialog

app.json, components/cards/ConfirmationCode.tsx, constants/patterns.ts, package-lock.json, package.json, screens/Authentication/SignUp/CreateCredentials.tsx
=> feat: add verification fields and update app version

contexts/AuthContext.tsx
=> Fix: Tap to edit functionality

components/lists/Signaling.tsx
=> refactor: update none of your friends online text

utils/share.ts
=> refactor: update the auto-invite  message on Share

components/CredentialsButton.tsx, constants/account-setup-steps.ts, contexts/AuthContext.tsx, libs/handleApiSignIn.ts, screens/Authentication/SignUp/CreateCredentials.tsx, types/index.ts, utils/index.ts
=> feat: swap user full names

app.json, package.json
=> feat: update version and disable tablet

constants/account-setup-steps.ts
=> fix: change the full name placeholder

components/AlertDialog.tsx
=> fix: change the body text font

components/Activity.tsx, components/cards/Status.tsx, components/lists/Friends.tsx
=> Fix: fonts and size in the edit status screen

screens/Home/index.tsx
=> fix: center NoFriends card

components/cards/UserAvailability.tsx, components/cards/UserStatus.tsx, package-lock.json
=>  fix Status line spacing

components/AlertDialog.tsx, components/AnimatedSwitch/index.tsx, components/cards/Action.tsx, components/cards/Header.tsx, components/lists/Signaling.tsx, theme.ts
=> Fix: semibold font weight on android

components/AlertDialog.tsx
=> Feat: update alert dialog spacings

components/cards/Action.tsx, components/cards/FriendsSkeleton.tsx, screens/EditSignal/index.tsx, screens/Search/index.tsx, screens/Settings/index.tsx
=> Feat: update notification action card

components/cards/UserAvailability.tsx, components/cards/UserStatus.tsx
=> feat: update user status card

components/Activity.tsx, components/cards/Status.tsx, components/lists/Friends.tsx, components/ui/CheckBox.tsx, components/ui/Input.tsx, screens/EditActivity/index.tsx, screens/EditSignal/index.tsx
=> Style: Change spacings in the "editSignal" screen

contexts/AuthContext.tsx, queries/friends.ts, queries/points.ts, queries/signal.ts, queries/user.ts, screens/EditSignal/index.tsx, screens/Home/index.tsx, screens/Search/index.tsx
=> refactor: move the queries and mutiations to separate files

screens/EditSignal/index.tsx
=> Fix: optimistic update new signal

components/lists/Friends.tsx
=> feat: update select all design

screens/EditSignal/index.tsx
This is refactoring the fixes for signal editing optimistic update implemented in PR #419 which was closing ticket #415
=> Refactor: Signal editing optimistic update

screens/NotificationPreferences/index.tsx
=> fix: update spacing of the notification preferences list

components/lists/Signaling.tsx, hooks/useEnableFriendNotification.ts, queries/friends.ts, types/index.ts
=> fix: improve friends notification enabling instant

components/SetActivity.tsx, components/ui/Badge.tsx, components/ui/CustomText.tsx, components/ui/CustomTitle.tsx
=> fix: improve input resize feature by removing the use of state

components/Friend.tsx, components/ui/HeaderWrapper.tsx, navigation/index.tsx, queries/groups.ts, screens/Groups/CreateGroup.tsx
=> feat: introduce create group screen

App.tsx
We are sending notifications however no badges [`The counter for notification`] at the moment. Changes I have possible will enable these badges
=> feat: Add notification badges

queries/signal.ts, screens/EditSignal/index.tsx
=> refactor: remove turnSignal request

components/lists/Signaling.tsx
=> Fix: show non of your fiends wavved when onlineFriends is empty

components/SetActivity.tsx
=> feat: set status text to empty when its one of the options

screens/Groups/index.tsx, types/index.ts
=> feat: display group info in the bottom sheet

components/BottomDrawer.tsx
=> fix: points badge showing on top of bottom drawer

components/SetActivity.tsx, components/cards/UserAvailability.tsx, components/cards/UserStatus.tsx, package-lock.json
=> fix: remove the lines limit on the signal activity

contexts/AuthContext.tsx, queries/friends.ts
=> fix: prefetch friends signal

utils/share.ts
Add download Link when a user shares an invite link
=> feat: add download link side the shared link

components/DatePicker.tsx, components/cards/Status.tsx, contexts/StatusContext.tsx, queries/signal.ts, screens/EditSignal/index.tsx
=> feat: highlight timeslot at all times

contexts/StatusContext.tsx
=> fix: add appstate listener to watch if date has ended

components/DatePicker.tsx, components/cards/Status.tsx
=> fix: open date picker if the signal has a custom timeslot

contexts/AuthContext.tsx, screens/Authentication/index.tsx
=>  resolve issue where user has to click multiple times on the sign in button to work 

components/lists/Signaling.tsx, screens/Home/index.tsx
=> feat: move the search button

components/Audience.tsx, components/BottomDrawer.tsx, components/cards/Action.tsx, components/cards/Status.tsx, components/lists/Friends.tsx, components/lists/Groups.tsx, components/lists/Signaling.tsx, components/lists/signaling/index.tsx, components/lists/signaling/signalingHeader.tsx, contexts/StatusContext.tsx, queries/signal.ts, screens/EditSignal/index.tsx, screens/Home/index.tsx, types/index.ts
=> feat: add audience selection in EditSignal
